#full app 

networks:
  dev:


services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    networks:
      - dev

  frontend:
    build:
      context: ./frontend
    networks:
      - dev

  backend:
    build:
      context: ./backend
    depends_on:
      - db
    networks:
      - dev

  db:
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=vlru
    ports:
      - 5432:5432
    volumes:
      - postgres-vlru-volume:/var/lib/postgresql/data
    networks:
      - dev

volumes:
  postgres-vlru-volume:
